apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: aurora-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aurora
  minReplicas: 2      # never go below 2
  maxReplicas: 20     # scale up to 20 for stress testing
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70  # scale up when CPU > 70%
